// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8hxKkGUEggLoOXiv8iAwC0BIR9BmJ3go',
    appId: '1:636309987955:web:f38774e1d557cd2d854006',
    messagingSenderId: '636309987955',
    projectId: 'hious-rider-app',
    authDomain: 'hious-rider-app.firebaseapp.com',
    storageBucket: 'hious-rider-app.appspot.com',
    measurementId: 'G-SKMEFSTTM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGqjiV9TtNyXJEhq5lxcKhZeoZX0nLtwM',
    appId: '1:636309987955:android:287acfd0f4045479854006',
    messagingSenderId: '636309987955',
    projectId: 'hious-rider-app',
    storageBucket: 'hious-rider-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMajEu9j5TXhY0cq5M0wcrYZ0xBEPqftQ',
    appId: '1:636309987955:ios:2afa8e20a4bcb478854006',
    messagingSenderId: '636309987955',
    projectId: 'hious-rider-app',
    storageBucket: 'hious-rider-app.appspot.com',
    iosClientId: '636309987955-0lc45f1fphnlr9jepdqq039su94rbvi5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiousRiderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMajEu9j5TXhY0cq5M0wcrYZ0xBEPqftQ',
    appId: '1:636309987955:ios:2afa8e20a4bcb478854006',
    messagingSenderId: '636309987955',
    projectId: 'hious-rider-app',
    storageBucket: 'hious-rider-app.appspot.com',
    iosClientId: '636309987955-0lc45f1fphnlr9jepdqq039su94rbvi5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiousRiderApp',
  );
}
